// This file was procedurally generated by Weaver. Any modifications will be overwritten.

#pragma warning disable // All.

/// <summary>This class was procedurally generated by Weaver.</summary>
public static class Animations
{
    #region Hash Constants

    /// <summary>Shark Swim 1</summary>
    public const int SharkSwim1 = 2079898214;

    /// <summary>Swim</summary>
    public const int Swim = 780061838;

    /// <summary>Get the name of the specified 'state' using HashToString.</summary>
    public static string GetName(this UnityEngine.AnimatorStateInfo state) => HashToString(state.shortNameHash);

    /// <summary>Get the state or parameter name associated with the specified 'hash' value.</summary>
    public static string HashToString(int hash)
    {
        switch (hash)
        {
            case SharkSwim1: return "Shark Swim 1";
            case Swim: return "Swim";
            default: return null;
        }
    }

    #endregion
}
