// This file was procedurally generated by Weaver.Editor.Procedural.BuildDetailsScriptBuilder.GenerateScript. Any modifications will be overwritten.

#pragma warning disable // All.

namespace Weaver
{
    /// <summary>
    /// A utility class which tracks the number of times this project has been built and the date it was last built.
    /// This class is automatically regenerated each time the project is built.
    /// </summary>
    public static class BuildDetails
    {
        /// <summary>The number of times this project has been built.</summary>
        public const int BuildNumber = -1;

        /// <summary>07/02/2022 21:32:36</summary>
        public static readonly System.DateTime BuildDate = new System.DateTime(637798663562779829L);
    }
}
