// This file was procedurally generated by Weaver. Any modifications will be overwritten.

#pragma warning disable // All.

namespace Weaver
{
    /// <summary>This class was procedurally generated by Weaver.</summary>
    [UnityEngine.DefaultExecutionOrder(-20000)]
    [UnityEngine.AddComponentMenu("")]
    internal sealed class Injector : UnityEngine.MonoBehaviour
    {
        [UnityEngine.SerializeField]
        private UnityEngine.Object[] _Objects;

#if UNITY_EDITOR // Editor.

        /// <summary>This property is here to give a compile error if you delete Weaver so you delete this script as well.</summary>
        [Weaver.AssetReferenceAttribute]
        private bool Dummy
        {
            set { }
        }

#endif

        #region Obsolete Members
#if UNITY_EDITOR

        [System.Obsolete("Remove any references to it.")]
        private static void OnApplicationStart() { throw new System.NotImplementedException("Weaver.Injector.OnApplicationStart is obsolete. Remove any references to it."); }

#endif
        #endregion
    }
}
