// This file was procedurally generated by Weaver. Any modifications will be overwritten.

#pragma warning disable // All.

/// <summary>This class was procedurally generated by Weaver.</summary>
public static class Layers
{
    #region Layers -> Edit/Project Settings/Tags and Layers

    /// <summary>Default (Mask Value = 1)</summary>
    public const int Default = 0;

    /// <summary>TransparentFX (Mask Value = 2)</summary>
    public const int TransparentFX = 1;

    /// <summary>Ignore Raycast (Mask Value = 4)</summary>
    public const int IgnoreRaycast = 2;

    /// <summary>Water (Mask Value = 16)</summary>
    public const int Water = 4;

    /// <summary>UI (Mask Value = 32)</summary>
    public const int UI = 5;

    #endregion
}
