// This file was procedurally generated by Weaver. Any modifications will be overwritten.

#pragma warning disable // All.

/// <summary>This class was procedurally generated by Weaver.</summary>
public static class Scenes
{
    /// <summary>Returns the name of the scene associated with the specified scene 'index' in the build settings.</summary>
    public static string IndexToName(int index)
    {
        switch (index)
        {
            default: return null;
        }
    }
}
